import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/provider/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen h-screen">
        {/* Redux 프로바이더 선언 */}
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
